# Generated by Django 4.2.5 on 2024-08-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockInfo",
            fields=[
                ("block_id", models.AutoField(primary_key=True, serialize=False)),
                ("block_name", models.CharField(default="undefined", max_length=128)),
                ("block_name_zh", models.CharField(default="未定义", max_length=128)),
                ("block_function", models.TextField(default="none")),
                ("lang", models.CharField(default="unselected", max_length=16)),
                ("in_module", models.CharField(default="none", max_length=128)),
                ("code", models.TextField(default="none")),
            ],
            options={
                "verbose_name": "BlockInfo",
                "verbose_name_plural": "BlockInfo",
                "db_table": "block_info",
                "ordering": ["block_id"],
            },
        ),
        migrations.CreateModel(
            name="CodeHierarchy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_leaf", models.BooleanField(default=True)),
                (
                    "block_id",
                    models.ForeignKey(
                        db_column="block_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.blockinfo",
                    ),
                ),
                (
                    "superior_block_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="superior_block_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.codehierarchy",
                    ),
                ),
            ],
            options={
                "db_table": "code_hierarchy",
            },
        ),
    ]
