# Generated by Django 4.2.5 on 2024-08-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codehierarchy",
            name="block_id",
            field=models.ForeignKey(
                db_column="block_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inferior_blocks",
                to="archive.blockinfo",
            ),
        ),
        migrations.AlterField(
            model_name="codehierarchy",
            name="superior_block_id",
            field=models.ForeignKey(
                blank=True,
                db_column="superior_block_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="superior_blocks",
                to="archive.blockinfo",
            ),
        ),
    ]
