# Generated by Django 4.2.5 on 2024-08-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0002_alter_codehierarchy_block_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockinfo",
            name="block_name",
            field=models.CharField(default="undefined", max_length=128, unique=True),
        ),
    ]
